### ISSUE TITLE
Can't use HOME variable for windows

### ISSUE THREAD

**Issue by TimonPost** [actions/starter-workflows#108]
As noted [here](https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables) I should be able to use the `HOME` variable to get the home folder location.

So in my script, I do the following:

```yaml
name: Rust

on:
  push:
    branches:
    - master
jobs:
  test:
  build:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows_latest]
    steps:
    - uses: actions/checkout@v1
      run: ${HOME}/.cargo/bin/cargo build --verbose
```

Although on windows, I get the error: `'${HOME}' is not recognized as an internal or external command,`, and on the other OS'ses it just works out fine, any idea how?
