### ISSUE TITLE
TERM environment variable not set.

### ISSUE THREAD

**Issue by methmal66** [actions/starter-workflows#1126]
Yarn test on github actions not working as expected. Displays the following error logs
```
>Run yarn test
yarn run v1.22.11
$ clear && jest --no-cache
TERM environment variable not set.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1. 
```
### actions taken to fix the error
moved to npm from yarn

commands `set | grep TERM` and `export TERM=xterm` commands were tested according to [this](https://stackoverflow.com/a/16252511) article. Only the installation of node_modules was possible using them.

### workflow
```
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest

      strategy:
         matrix:
            node-version: [12.x, 14.x, 16.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
         - uses: actions/checkout@v2
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v2
           with:
              node-version: ${{ matrix.node-version }}
         - run: export TERM=xterm
         - run: yarn install
         - run: yarn test
```

### environment
<ol>
<li>runs-on : ubuntu-latest</li>
<li>node-version: [12.x, 14.x, 16.x]
</ol>
