### ISSUE TITLE
Question: workflow_run event to filter by tags

### ISSUE THREAD

**Issue by syrils** [actions/starter-workflows#1137]
I wanted to check if there's support for filtering tags from a workflow_run event. Have the below sample workflows set up and working correctly for branches. But this does not work (workflow Two not triggered for tag push) for the `push a new tag` event. For example, using the git command:

`git tag -a v1.0.0 -m 'source=manual,branch=master,tag=v1.0.0' && git push --tags`

Workflow One:
```
name: Testing

on:
  push:

jobs:
  test-coverage:
  // do something
 
```

Workflow Two:
```
name: Deploy
on:
  workflow_run:
    workflows:
      - Testing
    types:
      - completed
    branches:
      - main
      - master
    tags:
      - v*.*.*
```
The docs mention a point regarding filtering by branch and nothing related to tags.

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run

`If you need to filter branches from this event, you can use branches or branches-ignore.`

If tags are not supported for workflow_run at the moment, any recommended workaround would be much appreciated. Thanks.

**Comment by yribeiro** [comment]
Has anyone found a good solution to this? I am having the same problem. The second workflow triggered with workflow_run does not execute when the original workflow is triggered with release.

**Comment by nk-hirai** [comment]
It appears that we can indeed specify tags using the `branches` filter. This approach has worked for me:
```yaml
on:
  workflow_run:
    branches: ['v*.*.*']
```
