### ISSUE TITLE
Docker .env action 

### ISSUE THREAD

**Issue by dkpaST** [actions/starter-workflows#1173]
Does anyone know how I can configure github actions to read the .env of my system?

```
- name: Start containers
        env:
          DB_USERNAME: ${{env.DB_USERNAME}}
          DB_PASSWORD: ${{env.DB_PASSWORD}}
          DB_DATABASE: ${{env.DB_DATABASE}}
          DB_PORT: ${{env.DB_PORT}}
        run: docker-compose -f "docker-compose.yml" up -d --build database redis
```

As it is, it doesn't load the variable's values.
