### ISSUE TITLE
slepp will hang more than provided

### ISSUE THREAD

**Issue by aaadipop** [actions/starter-workflows#1247]
hey,

I'm trying to add a timeout of 30s like:
```
    - name: Sleep
       run: sleep 30
```
or 
```
     - name: Sleep for 30s
        uses: juliangruber/sleep-action@v1.0.1
        with:
          time: 30s
```
or
```
    - name: Wait for connection
       run: ping 10.10.1.2 -c 3 -i 5 -t 20
```

but all of those are hanging for minutes

am I missing something?
