### ISSUE TITLE
Example workflow that commits and pushes to github

### ISSUE THREAD

**Issue by matham** [actions/starter-workflows#125]
This is a request to add a workflow example that commits to a branch and then pushes to it. Currently, there seems to be no examples showing how to do this.

My use case is that on each change to master, I run sphinx to automatically generate docs, and then push to `gh-pages`.

This worked before using a ssh key on e.g. appveyor. But when porting I wanted to see if I can just use the `GITHUB_TOKEN` for this, so I set
```
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
And
```
git config --global user.email "email@gmail.com"
git config --global user.name "My Name"
```
and then tried to push. Unfortunately, I then get a `fatal: could not read Username for 'https://github.com': No such device or address` error.

**Comment by peaceiris** [comment]
FYI.

- [peaceiris/actions-gh-pages: GitHub Actions for deploying to GitHub Pages with Static Site Generators](https://github.com/peaceiris/actions-gh-pages)

```yaml
name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Build
      run: mkdocs build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
```
