### ISSUE TITLE
Using expression as docker image for action

### ISSUE THREAD

**Issue by mosteo** [actions/starter-workflows#137]
First, I apologize if this is not the proper venue for this kind of question.

I'm trying to create an action that runs in a docker image which is given in an input parameter, but it seems the expression is not working:

```yaml
inputs: 
  docker-image:
    description: 'A dockerhub image with a particular tool in its $PATH'

runs:
  using: 'docker'
  image: 'docker://${{ inputs.docker-image }}'
  args: [ 'tool' ]
```
This is done to test this tool in several custom environments prepared as dockerhub images. The error I get is:
```
##[error](Line: 16, Col: 10): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.docker-image
```
The same expression works, e.g., in the `args:` value.

I have tested that I can work around this by pulling/running these docker images in a workflow (even using a matrix configuration), so the issue is relatively minor. Still, I wonder if this should work or if there is a good reason why this isn't a good idea.
