### ISSUE TITLE
publish tags matching regex

### ISSUE THREAD

**Issue by PascalSalesch** [actions/starter-workflows#145]
Hello,

does anyone have an idea how I could get `on.push.tags` to work?

I'm not sure if regexes are supported at all or if the yaml syntax allows any workaround

```yaml
name: Publish Github Package Repository

on:
  push:
    tags:
      - /^v\\d+(?!-(alpha|beta))\.\\d+(?!-(alpha|beta))\.\\d+(?!\-(alpha|beta))$/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@pascalsalesch'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.BOT_GITHUB_TOKEN}}
```

Thank you very much for your help

Alternatively, how could I ensure that 'v*' does not contain `-alpha` or `-beta`?
