### ISSUE TITLE
Create a php template

### ISSUE THREAD

**Issue by tiagobrito** [actions/starter-workflows#15]
It's a bit sad not to see PHP included in this first release.

**Comment by mscoutermarsh** [comment]
Definitely. We're on it. Unfortunately didn't get it done in time to release today.

**Comment by franzliedke** [comment]
Here's an example that works nicely for me:

~~~php
name: CI

on: [push]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Composer dependencies
      run: composer install --prefer-dist
    - name: Check code style
      run: php vendor/bin/phpcs --standard=PSR2 -np src

  phpspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
    steps:
    - uses: actions/checkout@v1
    - name: Install Composer dependencies
      run: composer install --prefer-dist
    - name: Run tests
      run: php${{ matrix.php }} vendor/bin/phpspec run
~~~

It still has room for improvement, but it gets the job done for now. (Most importantly, I would love to see an official `setup-php` action, without which I cannot guarantee which PHP version is used for e.g. `composer` runs and the first `vendor/bin/phpcs` execution.)

**Comment by spaceemotion** [comment]
Thanks for the template, @franzliedke. 

Just in case others stubmle upon this ticket, here's my setup:
1. I've added prestissimo for faster installs (over 10 seconds shaved from the total time), 
2. Added the validate command to make sure the .json is in sync with the .lock file
3. `--no-progress --no-suggest` disable other useless log output
4. Used phpunit instead of phpspec

```yml
name: CI

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate composer files
      run: composer validate --no-check-all --strict
    - name: Install prestissimo for faster installs
      run: composer global require hirak/prestissimo
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run tests
      run: php vendor/bin/phpunit
```

**Comment by shivammathur** [comment]
Hi, I created a action to setup PHP with required extensions and composer.
https://github.com/shivammathur/setup-php

For testing with one PHP version
```yaml
steps:
- name: Checkout
  uses: actions/checkout@master
- name: Setup PHP
  uses: shivammathur/setup-php@master
  with:
    php-version: 7.3
    extension-csv: zip, xdebug
```

For matrix testing with multiple OS and multiple PHP versions [See](https://github.com/shivammathur/setup-php#matrix-testing)
