### ISSUE TITLE
Make hub-cli pre-installed on all VMs

### ISSUE THREAD

**Issue by DrSensor** [actions/starter-workflows#151]
> from https://github.com/github/hub/issues/2249#issuecomment-536287903

Since [hub][] cli maintained by GitHub and it does a lot of thing related to GitHub operation, It would be nice if hub cli is pre-installed on all github action VMs 🥺

Currently I use [hub][] to do automated releases, but I need to install it first which is quite hassle.

My current workaround for setting up [hub][] cli
```yml
  job1:
    runs-on: ubuntu-latest
      steps:
      - name: Install hub.github.com
        run: |-
          wget -nv 'https://glare.now.sh/github/hub/.*linux-amd64.*.tgz' -O /tmp/hub-latest.tgz
          mkdir hub-latest && tar xf /tmp/hub-latest.tgz --strip=1 -C hub-latest
          cd hub-latest && sudo ./install
          rm -r ../hub-latest /tmp/*.tgz
          hub --version
```

cc: @bryanmacfarlane 

[hub]: https://hub.github.com
