### ISSUE TITLE
GitHub Context not being set properly

### ISSUE THREAD

**Issue by chingc** [actions/starter-workflows#153]
Hi, I'm not sure if this is the right place to post this, but I'm experiencing an issue where the github context isn't setting `ref` and `sha` properly.  The only recently started happening in the past 30 mins.

The following produces the github context json with empty strings as the `ref` and `sha`.

```
- name: Dump GitHub context
  env:
    GITHUB_CONTEXT: ${{ toJson(github) }}
  run: echo "$GITHUB_CONTEXT"
```

```
{
  "token": "***",
  "ref": "",
  "sha": "",
   ... other stuff
}
```

In the future, where can report issues if this is the wrong place?  Thanks.
