### ISSUE TITLE
Run script file for Linux and Windows

### ISSUE THREAD

**Issue by Sebazzz** [actions/starter-workflows#154]
In my repository I have a script file "build.sh" for Linux and "build.cmd" or "build.ps1" for Windows. Linux or Windows, the parameters of these files are the same. 

How do I either script without duplicating my steps?

Currently I have steps like:

```
            - name: Build - restore nuget packages (windows-only)
              if: contains(matrix.os, 'windows')
              run: .\build.cmd --target=restore-nuget-packages --verbosity=verbose

            - name: Build - restore nuget packages (linux-only)
              if: !contains(matrix.os, 'windows')
              run: ./build.sh --target=restore-nuget-packages --verbosity=verbose
```

Repeating this seems very cumbersome.

Is there perhaps the possibility to set some variable to the script file? Or automatically set the extension/command used?

**Comment by Sebazzz** [comment]
Apparently you can use/abuse the matrix for this:

```
        strategy:
            matrix:
                os: [windows-2019, ubuntu-16.04]
                include:
                    - os: windows-2019
                      script_name: .\build.cmd
                    - os: ubuntu-16.04
                      script_name: ./build.sh
```

Then in the action:

```
            - name: Build - restore nuget packages
              run: ${{ matrix.script_name }} --target=restore-nuget-packages --verbosity=verbose
```
