### ISSUE TITLE
How should I build in a specified folder

### ISSUE THREAD

**Issue by Jzow** [actions/starter-workflows#1566]
this is my action file:
```
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: mybatis/Cargo.toml
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

```
[my repo url](https://github.com/summer-rust/summer-mybatis)
