### ISSUE TITLE
Job environment can't access services

### ISSUE THREAD

**Issue by linuxjuggler** [actions/starter-workflows#158]
I was happy to know that the global environment is now alive and can be within the job or the workflow (https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#env-at-the-workflow-and-job-level)

but for some reason, the env at the job level can't access any information about the services, for example, something like the following

```yml
name: CI
on: [push, pull_request]
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      DB_PORT: ${{ job.services.mysql.ports['3306'] }}
      DB_PASSWORD: password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
```
Will not work, neither  

```yml
jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      DB_PORT: ${{ services.mysql.ports['3306'] }}
      DB_PASSWORD: password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis    
```

The error I get back:

> - Your workflow file was invalid: The pipeline is not valid. .github/workflows/ci.yml (Line: 26, Col: 16): Unrecognized named-value: 'job'. Located at position 1 within expression: job.services.mysql.ports['3306']

Any idea how to fix that, other than moving the env to the task that need to connect to the database?
