### ISSUE TITLE
Are the Python steps in azure-webapps-python.yml pointless?

### ISSUE THREAD

**Issue by jakeprice-me** [actions/starter-workflows#1669]
Hello, I wonder if somebody would be able to clarify why you include the below steps in [deployments/azure-webapps-python.yml](https://github.com/actions/starter-workflows/tree/main/deployments/azure-webapps-python.yml)

We're experimenting with Azure App Service, and this is the GitHub Actions workflow that gets automatically created for us when we link our repository to the deployment center.

```yaml
      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            . 
            !venv/
```

The reason I ask is because unless I am missing something obvious, are these steps not pointless? 

As far as I am aware, the steps are running on a GitHub Actions runner (running Ubuntu), _not_ on the App Service container (running Debian) that will run the web application, and because you can't easily copy a `venv` directory to another machine, why bother creating and activating a virtual environment, and then installing pip packages?

In fact in the very last step above, you explicitly _exclude_ the created `venv` directory from being included in the final artifact that gets deployed to App Service? 🤔 Is it running as some kind of test, to make sure the packages install _before_ deploying? If that's why you're doing it, I still wonder where the value in that is? The GitHub Actions runner is running Ubuntu, and the App Service container is running Debian 10/11 - so you couldn't guarantee you wouldn't run into issues when you deploy, even if the workflow passes?

I've seen this in a few places, similar steps are used in the sample workflow [here](https://github.com/Azure/actions-workflow-samples/blob/master/AppService/python-webapp-on-azure.yml) and another sample from an App Service team [blog post](https://azure.github.io/AppService/2020/12/11/cicd-for-python-apps.html) by @JasonFreeberg [here](https://github.com/Azure-Samples/djangoapp/blob/master/.github/workflows/build_and_deploy.yaml).

Any clarity on why you're doing this would be super helpful, because I don't think the docs make it clear at all.
