### ISSUE TITLE
Gradlew: Permission denied

### ISSUE THREAD

**Issue by WtfJoke** [actions/starter-workflows#171]
Hi there

I setup a new gradle workflow and have following error in my log:

```
Run ./gradlew build
/home/runner/work/_temp/46af0a17-aff6-47ea-ab02-304aec292273.sh: line 1: ./gradlew: Permission denied
```

I used following config (same as [gradle.yml](https://github.com/actions/starter-workflows/blob/master/ci/gradle.yml)):
```yml
name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
```

I fixed it by adding an additional step:
```yml
    - name: Make gradlew executable
      run: chmod +x ./gradlew
```

Is this a mistake? Or some issue on my end?
If you want I can make a PR for that.
