### ISSUE TITLE
Can I use another docker images at python-app.yml

### ISSUE THREAD

**Issue by LukeLIN-web** [actions/starter-workflows#1812]
I want to know whether I can use runs-on: torch/torch:1.12 instead of ubuntu-latest.
https://github.com/actions/starter-workflows/blob/e3b9c0d4bd8240b927aa0bda7958df94c3a2dd30/ci/python-publish.yml#L21

**Comment by LukeLIN-web** [comment]
> I think you are looking for https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
Thank you for your kind reply.
I have a problem. How do I run my git repository in a container?  Clone requires a username and input yes/no. 

```yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: 1263810658/pyg2.1-torch1.10-cuda11.3
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
```
