### ISSUE TITLE
Add SvelteKit starter

### ISSUE THREAD

**Issue by janosh** [actions/starter-workflows#1827]
Would be great to [have a starter](https://github.com/actions/starter-workflows/tree/main/pages) for people using [SvelteKit](https://github.com/sveltejs/kit) (approaching its 1.0 release).

**Comment by janosh** [comment]
Fwiw, this worked for me (uses `pnpm` as package manager):

```yml
# .github/workflows/docs.yml
name: Docs

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

# set permissions of GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true # allow one concurrent deployment

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install
          pnpm build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: build

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
