### ISSUE TITLE
Working cmake workflow:

### ISSUE THREAD

**Issue by erick-co** [actions/starter-workflows#196]
Working cmake workflow:
```
name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Debug
    - name: test
      run: cd build && ctest
```

_Originally posted by @rigtorp in https://github.com/actions/starter-workflows/issues/53#issuecomment-537847198_
