### ISSUE TITLE
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/xxxx

### ISSUE THREAD

**Issue by sunflower-knight** [actions/starter-workflows#2015]
![image](https://user-images.githubusercontent.com/70421213/232250392-106e4935-6a4b-46de-9620-695b3fe68ccd.png)

```yml
name: Compile Code Daily and Update cache

on:
  push:
    branches: [ main]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux-clang:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: ls dir
        run: |
          ls -al ./.github/workflows/linux.yml
          pwd
      - name: Build with Clang on Ubuntu 22.04
        uses: ./.github/workflows/linux.yml
```
I don't know why I wrong. The local workflow file exit in the path.
