### ISSUE TITLE
access vars or jobs context in run name or a PUT API for updating run name

### ISSUE THREAD

**Issue by rwader-swi** [actions/starter-workflows#2289]
Currently the name in workflow run has only access to `{{ inputs }}` and `{{ github }}` contexts, which is not very useful as we might **_want to display additional info which are processed in the job steps._**

- either give **access to `{{ job }}` context.** It might solve this as it will update name after the job step is completed (from outputs)
- or atleast **access the `{{ vars }}` context**, that we ultimately update in some job steps
- If not that then atleast **a PUT API endpoint for updating the run's metadata** like run-name.

Neither of the above are avaialable 🙂 
### **For example in my usecase we update our software version for every release run by 1. And we want to display in the run name.**

<img width="450" alt="image" src="https://github.com/community/community/assets/138435075/419cd263-421b-4d0c-9bda-e73efe063f04">

Will appreciate if anyone takes look into this feature ASAP!!!! And many people want this to be fixed.

**Comment by mmichna** [comment]
i think this is very useful feature allow update workflow `run-name`

**Comment by btungut** [comment]
Hi GitHub Actions Team,

It would be incredibly beneficial to have the ability to dynamically edit run_name within workflows. This feature would enhance traceability, improve monitoring, and streamline debugging by allowing more descriptive and contextual run identifiers. Please consider adding this functionality to make our CI/CD pipelines even more powerful.

Thank you!

**Comment by koder101** [comment]
I can confirm that this is working for me. Although the doc says that the `run-name` has only access to `{{ inputs }}` and `{{ github }}` contexts, but when I added a variable at the repository level (under Github secrets) and accessed it using the `vars.DEFAULT_ENVIRONMENT` surprisingly it worked.

May be this is an undocumented feature ( _bit reluctant to post if they remove it after its discovery_ 😁 ).

```
on:
  push:
    branches:
      - main
    paths:
      - 'abcd/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the deployment environment'
        required: false
        default: 'DEV'
        type: choice
        options:
          - DEV
          - UAT
          - PROD

run-name: '${{ github.event.inputs.environment || vars.DEFAULT_ENVIRONMENT }} - Run ID: ${{ github.run_id }} - by @${{ github.actor }}'
```
