### ISSUE TITLE
Pylint exit code 30

### ISSUE THREAD

**Issue by VinciGit00** [actions/starter-workflows#2303]
Hello to everyone, I used Github actions with Pylint. My overall score is 8.92 out of 10 and I still have the error number 30 Error: Process completed with exit code 30.
My configuration is the following:
`name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint yosoai/*.py
` and the link of the build is this: https://github.com/VinciGit00/YOSO-ai/actions/runs/7884270109/job/21512878900.
Is there anyone who can help me?

**Comment by AmberSahdev** [comment]
Facing the same. Following.

**Comment by AmberSahdev** [comment]
@VinciGit00 were you able to resolve this?

**Comment by Soft-Buddy** [comment]
@AmberSahdev Hi buddy,
I'm encountering the same issue. Here's a temporary workaround I found.
In the analyzing code part, modify it to be like : 
```
 - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --output=lint.txt || true
```

# Demo Workflow
```yaml
name: Pylint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --output=lint.txt || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lint.txt
          path: lint.txt
```
