### ISSUE TITLE
Getting error "bad indentation of a sequence entry on line 6 and the error (red underline) is showing under "turbostart-npm" YAML error

### ISSUE THREAD

**Issue by therookiecode5** [actions/starter-workflows#2335]
Getting error "bad indentation of a sequence entry on line 6 and the error (red underline) is showing under "turbostart-npm"
```
on:
  push:
    branches:
    - main
    - release/*
            - name: turbostart-npm
  uses: clutchd/turbostart-npm@v3.0.1
```
