### ISSUE TITLE
Error with Laravel action and application key

### ISSUE THREAD

**Issue by hightekjonathan** [actions/starter-workflows#271]
When using the default laravel action workflow, I get an error that the application key is never set even though I never modified the action workflow.

Here is my action code:
```
name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Clear config
      run: php artisan config:clear
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite 
      run: vendor/bin/phpunit
```

Here is the appropriate error in the action output:
```
There was 1 error:

1) Tests\Feature\ExampleTest::testBasicTest
RuntimeException: No application encryption key has been specified.

/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php:1123
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:48
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:24
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:787
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:667
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:615
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:767
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:925
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:853
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:818
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:667
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:615
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:767
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:215
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:189
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:354
/home/runner/work/hightekjonathan.com/hightekjonathan.com/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:170
/home/runner/work/hightekjonathan.com/hightekjonathan.com/tests/Feature/ExampleTest.php:17

ERRORS!
Tests: 2, Assertions: 1, Errors: 1.
##[error]Process completed with exit code 2.
```

It appears as if the PHPUnit command is run at the same time the key is generated. Has anyone else noticed this issue?
