### ISSUE TITLE
Loading environment variables from a file

### ISSUE THREAD

**Issue by ArtemIsmagilov** [actions/starter-workflows#2740]
Hello. You have the ability to load environment variables by one for tests.
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#env
```yaml
env:
  DAY_OF_WEEK: Monday
```
However, a test can contain a lot of variables. Adding and correcting these variables in a yaml file is extremely difficult.

Please add the ability to customize environment variables as is done in Docker containers through the env_file parameter.

Example. `env_file: example.env`

example.env
```text
A=1
B=2
C=3
```

```yaml
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
###
env_file: example.env
###
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Check env files $A $B $C"
```

Result
```bash
Check env files 1 2 3
```
