### ISSUE TITLE
Cannot use ${{}} in contexts in shell command

### ISSUE THREAD

**Issue by jbcpollak** [actions/starter-workflows#289]
I'm trying to use a custom shell command to set an rc file for bash. What I want to do is:

```
shell: bash --rcfile ${{ github.workspace }}/.github/workflows/bashrc -eo pipefail {0}
```

or use a short form like this:

```
env:
   SHELL: bash --rcfile ${{ github.workspace }}/.github/workflows/bashrc -eo pipefail {0}
...
# sometime later
- name: foo
  shell: ${{ env.SHELL }}
```

In both cases it appears the context cannot be resolved within the shell parameter, as I get this error:

```
- Your workflow file was invalid: The pipeline is not valid. .github/workflows/ci.yaml (Line: 23, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.SHELL,.github/workflows/ci.yaml (Line: 40, Col: 14): Unrecognized named-value: 'env'. Located at position 1 within expression: env.SHELL
```

I get a similar error for `github` when I try the other method as well.
