### ISSUE TITLE
how get get check run id

### ISSUE THREAD

**Issue by foxundermoon** [actions/starter-workflows#292]
`.../checks?check_run_id=372560184`

how to get the id ?

i want get the check url for notification action

**Comment by mscoutermarsh** [comment]
Hey @foxundermoon

You could probably make a request to the Checks API to find the ID for your run. Here are the [docs](https://developer.github.com/v3/checks/).

There isn't currently an easy way to grab it, you'd need to look at recent runs and figure out which one you need.

Good news is, we'll be adding an API soon that makes this easier (one request). And the response will include the URL to the page you need.

**Comment by afc163** [comment]
+1

**Comment by sarenameas** [comment]
Hello,

Is this API to get `check_run_id` available? It would be nice to get checks on a PR number or commit SHA.

**Comment by thebeline** [comment]
It is unfortunate that this was closed without a real resolution.  Has this been implemented?  This seems unnecessarily difficult...

**Comment by beccaduffield** [comment]
Yup

**Comment by thebeline** [comment]
> Hey @foxundermoon
> 
> You could probably make a request to the Checks API to find the ID for your run. Here are the [docs](https://developer.github.com/v3/checks/).
> 
> There isn't currently an easy way to grab it, you'd need to look at recent runs and figure out which one you need.
> 
> Good news is, we'll be adding an API soon that makes this easier (one request). And the response will include the URL to the page you need.

Like...  All of this is a lie:
- You can (and could) not make a request to the `Checks API` to "find the ID of your run."
- Depending on your Action language, the deployed configuration, and strategy/matrix, there is **NO** data provided that can reliably determine this in a "Production Ready" manner.
- "soon" is not the word I would use...

**Comment by nickofthyme** [comment]
I agree this is overly complicated to just obtain the check run id for the current job.

I had this issue trying to obtain the `run_id` or the current job in a workflow. I found a solution using the `actions` (not `checks`) api to [_List jobs for a workflow run_](https://docs.github.com/en/rest/reference/actions#list-jobs-for-a-workflow-run). You can pass the `github.run_id`, which is the action run not the check run!!

![image](https://user-images.githubusercontent.com/19007109/133908145-c24f6dbe-7138-42e0-b5fb-a457b541df5a.png)

## Usage in workflow

You can fetch the job run ids from within your workflow using [`octokit/request-action`](https://github.com/octokit/request-action). The catch is that you would need to somehow filter the response 

```yml
# .github/workflows/my_workflow.yaml
jobs:
  setup:
    name: Get check run ids from action run id
    runs-on: ubuntu-latest
    steps:
      - name: Fetch check run ids
        id: fetch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/actions/runs/{run_id}/jobs
          repo: ${{ github.repository }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo check run ids
        run: echo "job ids - ${{ toJSON(fromJSON(steps.fetch.outputs.data).jobs.*.id) }}

```

## Usage in custom action

You can use this rest api route via `listJobsForWorkflowRun` method from [`@actions/github`](https://github.com/actions/toolkit/tree/main/packages/github). This will return an array of job runs for the given action run. You would need to filter these to find the one you are looking for by name or something else.

```yml
# .github/workflows/my_workflow.yaml
jobs:
  setup:
    name: Get check run id from action run
    runs-on: ubuntu-latest
    steps:
      - name: My custom action
        uses: my/custom/actions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          input: 'something'
```

```ts
import * as github from '@actions/github';

const token = '**';

async function getJobId() {
  const octokit = await github.getOctokit(token);
  const { data } = await octokit.rest.actions.listJobsForWorkflowRun({
    ...github.context.repo,
    run_id: github.context.runId,
  });

  return data.jobs.find(({ name }) => name === 'MY RUN NAME')?.id ?? undefined;
}
```

> If you are using this in a job with [`jobs.<job_id>.strategy.matrix`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) you may need to pass the [`jobs.<job_id>.name`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idname) to find the correct one. Or use `String.prototype.startWith` using a common prefix (i.e. `PR #XX`).

---

Far from ideal but hope this helps someone 👍🏼
