### ISSUE TITLE
denied: Resource not accessible by integration

### ISSUE THREAD

**Issue by dalton-cole** [actions/starter-workflows#332]
When using the docker push starter workflow, exactly as-is from this repo, I get: `denied: Resource not accessible by integration` at the end of the push step. It had worked in the past but now it does not. Would my auto-generated token have somehow lost access to an existing package?

**Comment by dalton-cole** [comment]
If I create a personal access token and use that instead of piping in the GITHUB_TOKEN, the push works.

**Comment by ktori** [comment]
Having the same issue with a workflow that worked before for several weeks, failing on docker push now.

**Comment by dalton-cole** [comment]
@ktori as I mentioned above, if you create a personal access token with the right permissions, you can substitute that in via action secrets for now.

**Comment by dalton-cole** [comment]
I am also not able to delete package versions, I'm curious if this is related.

**Comment by ktori** [comment]
I contacted GitHub Support and they have resolved this issue in my repo, @dalton-cole if this was a site-wide issue it should be resolved for you too now.

**Comment by eine** [comment]
@ktori, I can confirm that it is fixed for me now. It worked for several months, it was failing during the last couple of day, but restarting the failed jobs now did work. Thanks for commenting about it!

**Comment by dalton-cole** [comment]
Issue appears to be resolved! Thanks @ktori and @eine for letting me know!

**Comment by glenn-jocher** [comment]
Seeing this error currently on PR greetings. Anytime someone submits a PR this happens:
<img width="766" alt="Screen Shot 2020-08-01 at 11 58 13 AM" src="https://user-images.githubusercontent.com/26833433/89108666-04d60200-d3ef-11ea-8c9c-2fd5f2c24cc6.png">

**Comment by vincerubinetti** [comment]
This is happening to me, seemingly out of no where (it seemed to be working just yesterday). https://github.com/actions/configure-pages/issues/40

Creating a PAT is unacceptable. The repo's actions permissions are already set to read and write by default. Also tried setting `permissions: write-all` on the job. Nothing is working.

**Comment by Hamza5** [comment]
As today in late 2023 (2023-12-09), this issue is still happening (and undocumented), and creating a **Personal Access Token with write access to GitHub Pages** is the solution for now.

This is how I implemented in in my workflow that builds a Flutter Web app and hosts it on GitHub Pages on every push:

```yaml
name: CI/CD
on:
  push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.x'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
      - name: Install Flutter packages
        run: flutter pub get
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v4
        with:
          token: ${{ secrets.PAGES_TOKEN }}
      - name: Build the Web app
        run: flutter build web --base-href="${{ steps.pages.outputs.base_path }}/" --dart-define=OWM_API_KEY=${{ secrets.OWM_API_KEY }}
      - name: Upload the Web app
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/web
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy the Web app
        id: deployment
        uses: actions/deploy-pages@v3
```

`PAGES_TOKEN` is a [_Personal Access Token_](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) that has **writing permession** to **Pages**.
