### ISSUE TITLE
environment substitution not work as expected

### ISSUE THREAD

**Issue by liudonghua123** [actions/starter-workflows#393]
I have a strategy configurations like the following.

```yml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: ${GITHUB_REPOSITORY##*/}-linux
          - os: macOS-latest
            output-name: ${GITHUB_REPOSITORY##*/}-mac
          - os: windows-latest
            output-name: ${GITHUB_REPOSITORY##*/}-windows.exe
```

However in the following steps where I use ${{ matrix.output-name }} in `windows-latest` environment, I got the incorrect `-windows.exe`.
