### ISSUE TITLE
How to check if the head branch match a specific pattern on branch pull request 

### ISSUE THREAD

**Issue by MahDevOps** [actions/starter-workflows#491]
I would like the write something like this inside my Github workflow action:
```
name: Deploy to branch with a specific pattern

on:
  pull_request:
    branches: master && contains(github.ref, 'myPattern') # The current head branch contains a specific word
```
However, it didn't work and I don't want to use if after running the job to stop it like following
name: Deploy to branch with a specific pattern

```
on:
  pull_request:
    branches: master

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'myPattern')
```
So any idea how to add condition to either run the action or don't run it at all based on head and target branch when a pull request happened
