### ISSUE TITLE
receiving yaml error: bad indentation of a mapping entry on 'steps'

### ISSUE THREAD

**Issue by mx1010** [actions/starter-workflows#508]
👋 hi all !

I'm unable to find anything specific to this error in this repository (yes it's probably bc its YAML specific) so I figured I'd make an issue anyway bc I am stuck.

<img width="520" alt="Screen Shot 2020-05-14 at 4 37 47 PM" src="https://user-images.githubusercontent.com/29803250/81983488-7b8a0d00-9601-11ea-86bb-f727d443e1b2.png">

Anyone know how to get rid of that error ? 😕

**Comment by mx1010** [comment]
Adding solution here for any future searchers!

Indentation was off under steps.

```
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - name: Login to DockerHub Registry
```
