### ISSUE TITLE
Improving the C++ Starter Workflow

### ISSUE THREAD

**Issue by TartanLlama** [actions/starter-workflows#53]
There's a couple of issues with the C++ starter workflow:

1. The template says it's for building a project with Make, but it's specifically targeted to projects which use Autotools as their build system, not bare Makefiles.
2. Few modern open source projects use Autotools: CMake is the de facto standard build system for C++ projects these days, especially cross-platform ones.

My suggestion would be to make the C++ starter workflow use CMake instead and potentially supply an Autotools-specific starter workflow as an additional option.

**Comment by kubasejdak** [comment]
YES, please listen to @TartanLlama. Almost all IDEs support it also, some of which use is as default option.

**Comment by lu-zero** [comment]
I'd consider giving the option of `meson` as well since it seems the current migration path from autotools for many big projects.

**Comment by chrispat** [comment]
We are happy to take a pull request for templates that you think will make sense.

**Comment by rigtorp** [comment]
It would also be good to have a starter workflow for MSVC builds. I'm trying to figure out how to build my CMake project using MSVC on GitHub Actions.

**Comment by rigtorp** [comment]
Working cmake workflow:
```
name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Debug
    - name: test
      run: cd build && ctest
```
