### ISSUE TITLE
Inconsistent styling of `.yml` files with regards to newlines after steps.

### ISSUE THREAD

**Issue by HonkingGoose** [actions/starter-workflows#532]
# What's the issue?

Inconsistent styling of `.yml` files with regards to newlines after steps.

## Example of issue:

Some `.yml` files have newlines after steps. (example from https://github.com/actions/starter-workflows/blob/master/ci/php.yml):
```
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
```

But some `.yml` files do not have newlines after each named step. (example from https://github.com/actions/starter-workflows/blob/master/ci/laravel.yml):

```
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
```

### Proposed Fix:

I find the style where each named step has their own 'block' to be more readable, therefore I propose that all steps have newlines after each block.

If this is something that the GitHub actions team wants, I'll fix it myself and make a pull-request for you. 😄
