### ISSUE TITLE
Dockerfile 

### ISSUE THREAD

**Issue by pascalandy** [actions/starter-workflows#59]
I just tested the Dockerfile CI example and it's working good :) 
Now to go all in, there are many step we need to put in place.

Here is my [.travis.yml ](https://github.com/firepress-org/ghostfire/blob/master/.travis.yml).

### define vars

```
before_script:
# define our labels and tags
  - GHOST_VERSION_DOCKERFILE="$(cat Dockerfile | grep GHOST_VERSION= | head -n 1 | grep -o '".*"' | sed 's/"//g')"
  - GHOST_LATEST_RELEASE="$(git ls-remote --tags https://github.com/TryGhost/Ghost.git | cut -d$'\t' -f2 | grep -E '^refs/tags/[0-9]+\.[0-9]+' | cut -d/ -f3 | sort -rV | head -n1)"
  - GHOST_CLI_LATEST_RELEASE="$(git ls-remote --tags https://github.com/TryGhost/Ghost-CLI.git | cut -d$'\t' -f2 | grep -E '^refs/tags/[0-9]+\.[0-9]+' | cut -d/ -f3 | sort -rV | head -n1)"
  - GHOST_VERSION=${GHOST_VERSION_DOCKERFILE}

  - DOCKER_USERNAME="devmtl"
  - DOCKER_REPO_NAME="ghostfire"
  - CONTAINER_NAME="ghostuat"

  - THIS_DATE=$(date +%Y-%m-%d)
  - THIS_SHA_SHORT=$(git rev-parse --short HEAD)

  - IMAGE_SHA_SHORT=${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:${GHOST_VERSION}-${THIS_SHA_SHORT}
  - IMAGE_VERSION=${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:${GHOST_VERSION}
  - IMAGE_STABLE=${DOCKER_USERNAME}/${DOCKER_REPO_NAME}:stable
```

### install:

```
  - echo "install microscanner Aquasec Scanner ==========>"
  - wget --retry-connrefused --waitretry=1 --read-timeout=5 --timeout=5 --tries=10 https://raw.githubusercontent.com/lukebond/microscanner-wrapper/master/scan.sh && chmod +x scan.sh

  - git clone https://github.com/docker-library/official-images.git ~/official-images
  - echo "Bypass timezone'stest "utc" as we use America/New_York timezone in our image ==========>"
  - sed -i "/utc/d" ~/official-images/test/config.sh
```

### build and run

```
script:
  - uname -a && echo & echo && echo "BUILD OUR DOCKERFILE FROM HERE ==========>"
  - docker build --build-arg=MICROSCANNER_TOKEN=${MICROSCANNER_TOKEN} -t ${IMAGE_SHA_SHORT} .
  - docker run -d --name ${CONTAINER_NAME} -p 2368:2368 -e url=http://localhost:2368 -e NODE_ENV=production ${IMAGE_SHA_SHORT}
  
  - echo & echo && echo "Ensure ${CONTAINER_NAME} is starting ==========>"
  - until $(curl --output /dev/null --silent --head --fail http://localhost:2368); do
      echo & echo && echo "Waiting for ${CONTAINER_NAME} container to run  ==========>";
      sleep 3;
    done
  - curl http://localhost:2368 | grep "The professional publishing platform"
```
### login

# docker hub log in
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin;

### push

```
after_success:
  - if [ ${TRAVIS_BRANCH} == "master" ] && [ ${DOCKER_REPO_NAME} != "" ] && [ ${DOCKER_USERNAME} != "" ] && [ ${DOCKER_PASSWORD} != "" ]; then

      docker push ${IMAGE_SHA_SHORT};

      docker build --build-arg=MICROSCANNER_TOKEN=${MICROSCANNER_TOKEN} -t ${IMAGE_VERSION} . ;
      docker push ${IMAGE_VERSION};

      docker build --build-arg=MICROSCANNER_TOKEN=${MICROSCANNER_TOKEN} -t ${IMAGE_STABLE} .;
      docker push "$IMAGE_STABLE";

      docker build --build-arg=MICROSCANNER_TOKEN=${MICROSCANNER_TOKEN} -t ${IMAGE_NODE_COMPRESS} --target node-compress . ;
      docker push "${IMAGE_NODE_COMPRESS}";

      docker build --build-arg=MICROSCANNER_TOKEN=${MICROSCANNER_TOKEN} -t ${IMAGE_NODE_CORE} --target node-core . ;
      docker push "${IMAGE_NODE_CORE}";

      docker build --build-arg=MICROSCANNER_TOKEN=${MICROSCANNER_TOKEN} -t ${IMAGE_GHOST_BASE} --target ghost-base . ;
      docker push "${IMAGE_GHOST_BASE}";

    fi
```

**Comment by pascalandy** [comment]
Overall, the template for Dockerfile should be pretty much the same for all Dockerfile :) We just need all the pieces of the puzzle :)

Thanks!

**Comment by pascalandy** [comment]
Ok I played with the concept and so far this is how it should looks like:

### A better template for docker

It's not perfect yet, but it's much better :)

```
name: Docker build CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build --file Dockerfile --tag devmtl/rclone:2.29.1-2019-08-24-32c812f7 .

      - name: Test docker official
        run: |
          git clone https://github.com/docker-library/official-images.git official-images
          official-images/test/run.sh devmtl/rclone:2.29.1-2019-08-24-32c812f7

      - name: Push docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push devmtl/rclone:2.29.1-2019-08-24-32c812f7
```

### ToDo

I still can't define variables :-/ I can only use variables define in the secrets section of the projet.

I'll open a new issue about this. Cheers!

### Improve docs

I would suggest to update the docs using a more realistic scenario. Feel free to close the issue.
