### ISSUE TITLE
Error: Resource not accessible by Integration

### ISSUE THREAD

**Issue by Vishruth-S** [actions/starter-workflows#677]
I added greetings to my repository, but I am getting the following error on pull requests submitted by new contributors.  
`Error: Resource not accessible by Integration`

![temp4](https://user-images.githubusercontent.com/55310756/96679651-b0a94100-1391-11eb-9b70-3db0a275cafe.png)

Here is my `greetings.yml` file
```yml
name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: ''
        pr-message: "Hi there :wave: Congratulations on sending your first Pull request here :sparkles:\n I hope that you have followed the contribution guidlines"
```

I tried searching for a solution to fix this but couldn't find one. So I am not sure if this is caused by something from my end or if this is some kind of a bug...
