### ISSUE TITLE
How to define env variable?

### ISSUE THREAD

**Issue by pascalandy** [actions/starter-workflows#68]
Hi,

I worked for few hours around the CI aspect of Github actions and the big piece that is missing is about how to define variables.

### my yml

```
name: Docker build CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build --file Dockerfile --tag devmtl/rclone:2.29.1-2019-08-24-32c812f7 .

      - name: Test docker official
        run: |
          git clone https://github.com/docker-library/official-images.git official-images
          official-images/test/run.sh devmtl/rclone:2.29.1-2019-08-24-32c812f7

```

### what I want to do

Of course, the tag `devmtl/rclone:2.29.1-2019-08-24-32c812f7` should be dynamic. I need to:

- generate the date
- find the hash from the actual commit

From there, I should be able to generate all the tags required.

See how I do this using Travis:
https://github.com/firepress-org/ghostfire/blob/master/.travis.yml#L45

Cheers!

**Comment by mscoutermarsh** [comment]
Hi @pascalandy!

Take a look here for setting env vars: https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables

**Comment by pascalandy** [comment]
Hello @mscoutermarsh, thanks for replying.

OK the big glitch I see in the fact that we need to redefine VAR at each steps:

> Create an environment variable for each action in your workflow file that needs access to the GITHUB_TOKEN secret:

I think this defeats the point of using VAR isn't?

**Comment by pascalandy** [comment]
About

> Take a look here for setting env vars: help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables

It's confusing that the docs you send me is not part of: https://help.github.com/en/categories/automating-your-workflow-with-github-actions

So:

- https://github.com/features/actions
- click on docs:
- https://help.github.com/en/categories/automating-your-workflow-with-github-actions
- then we are lost ...

**Comment by pascalandy** [comment]
### `with` or `env`
In this example ([source](https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables)):

```
steps:
- name: Hello world action
  with: # Set the secret as an input
    super_secret: ${{ secrets.SuperSecret }}
  env: # Or as an environment variable
    super_secret: ${{ secrets.SuperSecret }}
```

I don't understand with difference between `with` and env`.

**Comment by kangwonlee** [comment]
* If I may : (originally from https://github.com/actions/starter-workflows/issues/44#issuecomment-525696040)
* According to [jobs.<job_id>.steps](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idsteps)

> Each step runs in its own process in the virtual environment and has access to the workspace and filesystem. Because steps run in their own process, changes to environment variables are not preserved between steps.

* So could it be better to make one step rather longer if you don't want to set path frequently?

**Comment by kangwonlee** [comment]
@pascalandy Thanks for your opinion. What about adding a few `echo` lines? Could it be a little more comfortable?

> @kangwonlee That would make the logs a pain to read :-p
> 
> > So could it be better to make one step rather longer if you don't want to set path frequently?

**Comment by kangwonlee** [comment]
* @pascalandy Thanks for your opinion again
* IMHO, if each step could be more *functional*, would it be a more desirable direction?

**Comment by deitch** [comment]
Yeah, I am beginning to realize that this (job-wide or workflow-wide env vars) is one of several things that GH Actions is missing. I love the idea of the yml-defined workflow, and it all inside GitHub, but it looks like these use common use cases aren't properly addressed (quite yet, I can hope).

I had the same issue with conditions: setting conditions on a job. I can set it on a workflow, or a step, but not a job. Hmm, I should open an issue for this.

In any case, looking forward to seeing broader env vars.

**Comment by linuxjuggler** [comment]
@deitch it is not missing anymore, it is now alive https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#env-at-the-workflow-and-job-level

**Comment by deitch** [comment]
Oh good. One piece answered...

**Comment by richardbertozzo** [comment]
Hi, 

I'm trying something similar. I will upload a folder to AWS S3, but its not working. First i run the command of configure the secrets and after the command of publish.

My job:

```
- name: configure aws cli
  env:
    AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
    AWS_SECRET_ACCESS: ${{ secrets.AWS_SECRET_ACCESS }}
  run: aws configure set aws_access_key_id ${AWS_ACCESS_ID} && aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS}
```

So, the output is: 
`aws configure set aws_access_key_id *** && aws configure set aws_secret_access_key ***`

So the upload failed. It seens can't get the envs. I tried in others ways, but didn't work either. 

Someone have some idea?

**Comment by richardbertozzo** [comment]
I created a `Makefile` and its works. But has this example can be helpful https://github.com/jakejarvis/s3-sync-action

**Comment by andymckay** [comment]
Thank you @pascalandy, but we'd like to keep issues related to code in this repository. It looks like with https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#env-at-the-workflow-and-job-level you've got what you need. @pascalandy, @richardbertozzo and others:

* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

Thanks all.

**Comment by pascalandy** [comment]
I get that you guys made a "Github Actions" specific way of using ENV_VAR. I feel my solution is more agnostic. Anyways, I'll respect your point of view on this.

Cheers!

**Comment by nextgenthemes** [comment]
Can I not used env vars in with?

```
      - uses: actions/upload-artifact@master
        with:
          name: "$DEPLOY_ZIPFILE"
          path: "$DEPLOY_ZIPFILE"
```

This fails!

      - uses: actions/upload-artifact@master
        with:
          name: "{{ DEPLOY_ZIPFILE }}"
          path: "{{ DEPLOY_ZIPFILE }}"

This fails too...

And based in the error message it seems the artifact path needs to be relative ...

**Comment by smac89** [comment]
I found en even easier way buried somewhere in the [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-an-environment-variable-set-env) is this syntax:

```bash
::set-env name={name}::{value}
```

This is how you use it:

```bash
echo "::set-env name=APP_NAME::$(cat Dockerfile | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g')"
```

I know it's weird with the `echo`, but this actually works because it allows you to access the variable in proceeding steps.

**Comment by aeolus** [comment]
@smac89 it doesn't seem set-env work across jobs, seems only valid for the following steps in the same job.

I wonder if there is any way to pass such env var across jobs. My use case is building an RN app, one job on ubuntu and one job on osx, they need to share some vars like tag_name, build_number and such var could be based on datetime for example.

**Comment by dreamer** [comment]
Hmm, why this request was closed? 

https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#env-at-the-workflow-and-job-level says that env variable can be set at **workflow or job** level, but it's not true: it can be set at **job or step** level only (or at least only these are documented).

**Comment by eyal0** [comment]
The solution with the echo "::" is not bad.  You could wrap it in an action to make it even nicer to use.

**Comment by smac89** [comment]
@nextgenthemes See https://github.com/smac89/gh-actions-samples/blob/ffac4047d7d97409180efad5c503b4afb6c2a289/.github/workflows/step_param_from_env.yml#L21

**Comment by PoisonousJohn** [comment]
It seems that `::set-env` does not support multiline values. I'm trying to store multiline changelog in the env var, but it takes only first line

**Comment by ethomson** [comment]
Hello @PoisonousJohn - I'm afraid that this repository is not the best place to get assistance with that question.  This repository really only holds some sample workflows that are used when you're getting started with GitHub Actions, and doesn't take the environment variable configuration into account.

The [GitHub Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions) is the best place to ask as there are members of the product team and support team there who can help you solve this, or to file a bug in the product if indeed there is one.

Thanks!

**Comment by PoisonousJohn** [comment]
Sorry for the confusion. I was not requesting any assistance with the issue. It was just a note for anybody who encounters this thread as I am. Documentation is a bit unclear on it.
BTW: I was able to solve the issue by replacing all `\n` with %0A in case anybody would need that.

**Comment by ethomson** [comment]
Oh, sorry I misunderstood @PoisonousJohn.  Thanks much for the additional information!

**Comment by smeijer** [comment]
I think I'm missing something; shouldn't this be working?

Somehow, it still writes the release name as `$APP_NAME v1.0.0`

```yml
name: Build & Release

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: My App

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: $APP_NAME ${{ github.ref }}
          body: ${{ steps.prepare_release.outputs.changelog }}
          draft: false
          prerelease: false
```

**Comment by smeijer** [comment]
Never mind, as usual; I've figured it out 5 minutes after asking;

Instead of 

```yml
          release_name: $APP_NAME ${{ github.ref }}
```

We should use

```yml
          release_name: ${{ env.APP_NAME }} ${{ github.ref }}
```

**Comment by simontom** [comment]
Hello, not sure if this somehow helps (if it's not OT :-D ) but I started playing w/ Actions today.
And following piece of yml may help to someone

```
      - name: Create release APK name
        run: |
          export APK_NAME="release_$(date +'%Y-%m-%d')"
          echo "::set-env name=NEW_APK_NAME::$APK_NAME"
      
      - name: Rename release APK
        run: |
          mv "./app/build/outputs/apk/release/app-release-unsigned.apk" "./${{ env.NEW_APK_NAME }}.apk"
      
      
      
      - name: Persist release APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.NEW_APK_NAME }}
          path: "./${{ env.NEW_APK_NAME }}.apk"
```

**Comment by santisaez** [comment]
>Is there a way to define env variables via a `.env` file?

Hello 👋 I have reached here trying to solve the same thing 😄 

I have been able to workaround it looping the file and setting the env vars with the [`set-env` command](https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable):

```yaml
- name: Set ENV variables
  run: for v in `cat env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
```

`set-env` sets job-wide env variables, so they will be available in the subsequent steps.

**NOTE**: if the above one-liner grabs your attention, [this post](https://www.linuxjournal.com/article/8919) explains how key/values are extracted.

**Comment by destinybonavita** [comment]
Is there a way to run `echo "::set-env name=EXAMPLE::SECRET_KEY"` without it logging the output? I've tried running `::set-env` without `echo` but it didn't seem to work

**Comment by Fabioluxx** [comment]
`jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"`

**After you can use ${{steps.date.outputs.date}} to use a value.**

Source: https://github.community/t5/GitHub-Actions/How-can-I-set-an-expression-as-an-environment-variable-at/m-p/41804/highlight/true#M4751

**Comment by piyushsonigra** [comment]
You can set environment variables by saving it in ~/.bashrc or ~/.bash_profile in one step and by using source command you can export vars in other steps.

```
steps:
- name: Build-Deploy
    uses: actions/checkout@v2
- name: environment
    run: |
    echo "export ENV=DEV" > ~/.bashrc
- name: get_env
    run: | 
    source ~/.bashrc
    echo $ENV
```

**Comment by McArcady** [comment]
> Hello @PoisonousJohn - I'm afraid that this repository is not the best place to get assistance with that question. This repository really only holds some sample workflows that are used when you're getting started with GitHub Actions, and doesn't take the environment variable configuration into account.
> 
> The [GitHub Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions) is the best place to ask as there are members of the product team and support team there who can help you solve this, or to file a bug in the product if indeed there is one.
> 
> Thanks!

On the contrary I find the feedbacks very useful since the thread makes look like the problem has been solved but it's not.
It prevents developers from losing time trying to make the new 'env' features work, and documents the mandatory workarounds that could be missing from the community forums.

**Comment by dschinkel** [comment]
> @deitch it is not missing anymore, it is now alive https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#env-at-the-workflow-and-job-level

I don't understand how that would look with syntax.  It'd be nice if they actually showed an example

**Comment by jeacott1** [comment]
I'd just like to see a new category for secrets that isn't hidden and one way -  a not so secret option to set arbitrary env vars, and see/edit their values and they get applied like secrets to every build. every other CI server out there does this, why not actions??

**Comment by rytswd** [comment]
I understand this is an old issue, but I found it misleading how this issue hasn't referenced the [official documentation on Environment Files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).

With the new setup, rather than using  `::set-env` which is deprecated, it would look like below.

```yaml
jobs:
  date:
    runs-on: ubuntu-latest

    steps:
      - name: Get date
        run: |
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Echo env date
        run: |
          echo "${{ env.current_date }}"
```

Also, as mentioned in the doc, you can have more complex multiline setup.

```yaml

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
      - name: Get teapot
        run: |
          echo 'teapot<<EOF' >> $GITHUB_ENV
          curl https://httpbin.org/status/418 >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Echo env teapot
        run: |
          echo << 'EOF'
          ${{ env.teapot }}
          echo 'EOF'
```

Ref: [Example setup with the above YAMLs](https://github.com/rytswd/simple-github-actions/blob/main/.github/workflows/env-manipulation.yaml)

**Comment by danielo515** [comment]
Why is this so damn complicated? The internet is full of contradictory examples and workarounds that are probably out of date. The worst thing is that there are github DOCS containing both the, in theory duplicated, way and the new way.

Why all this syntax weirdos and hacky things? Why not stick to the same syntax as the rest of the stuff? Is it really that hard to allow:

```
- name: set env vars
   env:
       foo: bar
```

And maybe add a flag to decide if it should be set globally or not. C'mon, everytime I have to configure a workflow I spend more time looking for the right way of doing things than the time they will be running.

**Comment by eyal0** [comment]
@danielo515 Your suggestion seems half-baked.  Adding a flag is not going to make things more clear.

**Comment by danielo515** [comment]
@eyal0 it uses the same syntax as the rest of the steps. It seems intuitive to me. The only reason why I proposed a flag is because there is already an env directive. Maybe use a different name, like set-envs, but the current solution is not intuitive nor properly documented and does not work consistently across runners (windows machines for example)

**Comment by abranhe** [comment]
It took me a while to figure it out, but I got it working like this:

```yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: sudo apt update && sudo apt install -y jq
      - name: Name Generator
        run: |
          echo 'RANDOM_NAME='$(curl https://randomuser.me/api | jq '.results[0].name.first') >> $GITHUB_ENV
      - name: Display Name
        run: |
          echo ${{ env.AUTH_TOKEN }}
```
