### ISSUE TITLE
How to use environment secret on github action?

### ISSUE THREAD

**Issue by paulo-coutinho** [actions/starter-workflows#785]
Hi,

Im breaking my head understand how the environment secret works and how i can get this value from python.

I follow the docs and make two vars:

![image](https://user-images.githubusercontent.com/395096/105118813-da1b5b00-5aad-11eb-85fa-7ee6323f159c.png)

And i tried with:

```
- name: Ezored - Dist upload
  env:
    EZORED_AWS_KEY_ID: ${{ secrets.EZORED_AWS_KEY_ID }}
    EZORED_AWS_SECRET_KEY: ${{ secrets.EZORED_AWS_SECRET_KEY }}
  run: python make.py target ${{ matrix.config.target }} dist upload --force
```

and with:

```
- name: Ezored - Dist upload
  env:
    EZORED_AWS_KEY_ID: ${{ env.EZORED_AWS_KEY_ID }}
    EZORED_AWS_SECRET_KEY: ${{ env.EZORED_AWS_SECRET_KEY }}
  run: python make.py target ${{ matrix.config.target }} dist upload --force
```

Both python cannot get the value using ```os.getenv("EZORED_AWS_KEY_ID")```.

What i need do?

**Comment by AverageComet250** [comment]
Two things:

1. You should use `os.environ()` not `os.getenv()` as the environ command can also get environment variables from `.env` files.

2. Instead of putting it in your environmental variables and using the `os.environ()` command, you can just reference the secret directly. E.g. `secret = {{ secret.GIT_TOKEN }}`.

**Comment by madchap** [comment]
If you're using a fork model, it seems that it's not possible.

E.g. The upstream repo has the secrets configured. I push a PR from my fork. It's all empty.

Seems there is a way for private repo and all: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by konradpabjan** [comment]
Please direct questions like this to our community forum: https://github.community/c/code-to-cloud/github-actions/41

Issues in this repositories should only be related to our starter workflows 🙇‍♂️

**Comment by maheshmnj** [comment]
> 2\. `secret = {{ secret.GIT_TOKEN }}`.
@AverageComet250 
You mean we can directly access the token in code? 
I want to access in a dart programming language will that work?

**Comment by AverageComet250** [comment]
@maheshmnj I'm not fully sure you should try it yourself, and this post is dead since no one has used it for 2 months so you have technically necro posted

**Comment by maheshmnj** [comment]
okay thanks

**Comment by 123MwanjeMike** [comment]
You should enclose the variable in quotes.
Instead of this:
```
EZORED_AWS_KEY_ID: ${{ secrets.EZORED_AWS_KEY_ID }}
EZORED_AWS_SECRET_KEY: ${{ secrets.EZORED_AWS_SECRET_KEY }}
```
Do this:
```
EZORED_AWS_KEY_ID: '${{ secrets.EZORED_AWS_KEY_ID }}'
EZORED_AWS_SECRET_KEY: '${{ secrets.EZORED_AWS_SECRET_KEY }}'
```

**Comment by maheshmnj** [comment]
> You should enclose the variable in quotes.
> Instead of this:
> 
> ```
> EZORED_AWS_KEY_ID: ${{ secrets.EZORED_AWS_KEY_ID }}
> EZORED_AWS_SECRET_KEY: ${{ secrets.EZORED_AWS_SECRET_KEY }}
> ```
> 
> Do this:
> 
> ```
> EZORED_AWS_KEY_ID: '${{ secrets.EZORED_AWS_KEY_ID }}'
> EZORED_AWS_SECRET_KEY: '${{ secrets.EZORED_AWS_SECRET_KEY }}'
> ```

Thanks, I found the simplest way to do this answered here: https://stackoverflow.com/a/67998780/8253662

**Comment by ssi-anik** [comment]
@maheshmnj what's the difference between Paulo's yml settings and SO answer?

**Comment by maheshmnj** [comment]
@ssi-anik, I am not sure about his approach but one thing I understand is you cannot use Github secret outside of the yml file, regarding the SO approach you can read more in detail about it in the [medium blog post ](https://medium.com/flutter-community/managing-secrets-in-an-open-sourced-flutter-web-app-8c2219ed72b9  )

**Comment by BlossomWhale** [comment]
I don't know you're still finding solutions for this problem, but you could use environment secrets like this

Suppose that, we may define Environment secrets like this

![image](https://user-images.githubusercontent.com/85476751/133116919-0b6cbdf3-d52f-4549-bfa2-bb49dd85c07e.png)

and we could use like this

![image](https://user-images.githubusercontent.com/85476751/133117082-53a822e4-5d2a-4809-972a-e1e66bbe90e8.png)

i'm sorry for showing some unfinished test code but you may get some sure insight for just upside code that using 

environment: AWS_S3_CODEDEPLOY_KEY

or you may just refer these:

https://docs.github.com/en/actions/reference/environments#referencing-an-environment
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenvironment

as you could see above references, you may allocate environments for each jobs.

**Comment by theblueskies** [comment]
Maybe try this:

```
- name: Ezored - Dist upload
  env:
    EZORED_AWS_KEY_ID: ${{ env.EZORED_AWS_KEY_ID }}
    EZORED_AWS_SECRET_KEY: ${{ env.EZORED_AWS_SECRET_KEY }}
  run: EZORED_AWS_KEY_ID=$EZORED_AWS_KEY_ID EZORED_AWS_SECRET_KEY=$EZORED_AWS_SECRET_KEY python make.py target ${{ matrix.config.target }} dist upload --force
```

By including them as runtime options, it might just work you to get the secrets through `os.getenv` or `os.environ`
