### ISSUE TITLE
Global env variables?

### ISSUE THREAD

**Issue by chingc** [actions/starter-workflows#80]
Sorry if this isn't the right place to ask, but how can environment variables be set for the entire workflow?

I'm currently doing this whenever I need my local timezone:

```yaml
- name: Test
  env:
    TZ: America/New_York
  run: yarn run test
```

The problem is that I have to do this every time if I need to use my local timezone for anything.

How can this be set on a global level so it works across the entire run?

**Comment by pascalandy** [comment]
This is how I do it:
https://github.com/actions/starter-workflows/issues/68#issuecomment-524937002

**Comment by mscoutermarsh** [comment]
Hi @chingc, take a look at @chrispat's [response here](https://github.community/t5/GitHub-Actions/Support-global-environment-variables/m-p/30481#M441) for the plans on improving this.

**Comment by chingc** [comment]
@mscoutermarsh I'm very much looking forward to that change!

**Comment by linuxjuggler** [comment]
it is now a live https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#env-at-the-workflow-and-job-level

**Comment by chingc** [comment]
Thank you!

**Comment by zhangguanzhang** [comment]
could use for all jobs:
```yaml
name: Go

on:
  push:
    branches: 
     - test
     - master
env:
  key1: value1
jobs:
```
or for single jobs:
```yaml
jobs:
  build:
    name: Build
    env:
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }} 
```
