### ISSUE TITLE
Errors from Actios are now shown 

### ISSUE THREAD

**Issue by ackbyte** [actions/starter-workflows#850]
Hi,

I set up a linter job for repository and found an issue during the run on the linter job. The actions is not showing the full error-output so the error-message is unfortunately not completed and can not be understood from this output:

![Screenshot 2021-03-16 at 17 38 28](https://user-images.githubusercontent.com/683434/111346875-efac9b80-867e-11eb-9cb0-b75417ab67ff.png)

A run in a local docker container shows the proper issues with the path:
![Screenshot 2021-03-16 at 09 50 32](https://user-images.githubusercontent.com/683434/111347039-1c60b300-867f-11eb-8025-67e5cb6cf007.png)
Also the same on Ubuntu 18.04.5 LTS.

What is wrong? Why the action run is hiding or leaving the errors out with the correspondending lines.

Attach my .github/workflows/main.yml configuration:
```yaml
name: CI
on:
  push:
    branches:
    - '**'
    - '!main'
  pull_request:
    branches: [master]

  workflow_dispatch:
jobs:
  linting:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2

      - name: Install yamllint
        run: sudo apt update && sudo apt install -y yamllint

      - name: Run yamllinter against the automation repository
        run: cd $GITHUB_WORKSPACE/ && yamllint -c yamllint-conf.yml .
```
Current runner version: 2.277.1
Operating System: Ubuntu 18.04.5 LTS
