### ISSUE TITLE
Docs suggest different kind of auth for GPR

### ISSUE THREAD

**Issue by codeofsumit** [actions/starter-workflows#86]
The docs here:
> You can also use a GITHUB_TOKEN to push packages to the GitHub Package Registry in a GitHub Actions workflow. For more information, see "`GITHUB_TOKEN secret."

https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry#authenticating-to-github-package-registry

and here:

> Create an environment variable for each action in your workflow file that needs access to the GITHUB_TOKEN secret

https://help.github.com/en/articles/virtual-environments-for-github-actions#github_token-secret

suggest that the env name is `GITHUB_TOKEN` which does not work. As shows in this example workflow, it should be `NODE_AUTH_TOKEN`

Ideally, the correct env vars are documented 👍

**Comment by chrispat** [comment]
The correct ENV vars are documented.  The setup-node action configures your .npmrc to auth with a token in the `NODE_AUTH_TOKEN` environment variable.  That token value may or may not need to be the GITHUB_TOKEN secret depending on which registry you are pushing to.  

As shown in the GPR starter example you can set the `NODE_AUTH_TOKEN` environment variable to the GITHUB_TOKEN secret if you want to push to GPR.
```
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@your-github-username'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
