### ISSUE TITLE
python-publish  error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by talbiston** [actions/starter-workflows#887]
### Here is the yaml file as i have it.

```yaml
# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        python -m pip install --upgrade twine
 
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --repository testpypi dist/*
```

#### From what i can tell the "install dependencies" part is working as i see "Successfully installed wheel-0.36.2" in the output below 

```Run python -m pip install --upgrade pip
  python -m pip install --upgrade pip
  python -m pip install --upgrade setuptools
  python -m pip install --upgrade wheel
  python -m pip install --upgrade twine
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.4/x64/lib
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages (21.0.1)
Collecting pip
  Downloading pip-21.1-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.0.1
    Uninstalling pip-21.0.1:
      Successfully uninstalled pip-21.0.1
Successfully installed pip-21.1
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9/UNKNOWN
sysconfig: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages (49.2.1)
Collecting setuptools
  Downloading setuptools-56.0.0-py3-none-any.whl (784 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9/UNKNOWN
sysconfig: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Successfully installed setuptools-56.0.0
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9/UNKNOWN
sysconfig: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
Collecting wheel
distutils: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9/UNKNOWN
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
sysconfig: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9
WARNING: Additional context:
Installing collected packages: wheel
user = False
Successfully installed wheel-0.36.2
home = None
Collecting twine
root = None
  Downloading twine-3.4.1-py3-none-any.whl (34 kB)
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9/UNKNOWN
sysconfig: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting colorama>=0.4.3
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting pkginfo>=1.4.2
  Downloading pkginfo-1.7.0-py2.py3-none-any.whl (25 kB)
Collecting requests-toolbelt!=0.9.0,>=0.8.0
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting keyring>=15.1
  Downloading keyring-23.0.1-py3-none-any.whl (33 kB)
Collecting readme-renderer>=21.0
  Downloading readme_renderer-29.0-py2.py3-none-any.whl (15 kB)
Collecting importlib-metadata>=3.6
  Downloading importlib_metadata-4.0.1-py3-none-any.whl (16 kB)
Collecting requests>=2.20
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting tqdm>=4.14
  Downloading tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
Collecting rfc3986>=1.4.0
  Downloading rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.1-py3-none-any.whl (5.2 kB)
Collecting SecretStorage>=3.2
  Downloading SecretStorage-3.3.1-py3-none-any.whl (15 kB)
Collecting jeepney>=0.4.2
  Downloading jeepney-0.6.0-py3-none-any.whl (45 kB)
Collecting docutils>=0.13.1
  Downloading docutils-0.17.1-py2.py3-none-any.whl (575 kB)
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting bleach>=2.1.0
  Downloading bleach-3.3.0-py2.py3-none-any.whl (283 kB)
Collecting Pygments>=2.5.1
  Downloading Pygments-2.8.1-py3-none-any.whl (983 kB)
Collecting packaging
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting cryptography>=2.0
  Downloading cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
Collecting cffi>=1.12
  Downloading cffi-1.14.5-cp39-cp39-manylinux1_x86_64.whl (406 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pycparser, pyparsing, cffi, zipp, webencodings, urllib3, six, packaging, jeepney, idna, cryptography, chardet, certifi, SecretStorage, requests, Pygments, importlib-metadata, docutils, bleach, tqdm, rfc3986, requests-toolbelt, readme-renderer, pkginfo, keyring, colorama, twine
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9/UNKNOWN
sysconfig: /opt/hostedtoolcache/Python/3.9.4/x64/include/python3.9
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Successfully installed Pygments-2.8.1 SecretStorage-3.3.1 bleach-3.3.0 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 colorama-0.4.4 cryptography-3.4.7 docutils-0.17.1 idna-2.10 importlib-metadata-4.0.1 jeepney-0.6.0 keyring-23.0.1 packaging-20.9 pkginfo-1.7.0 pycparser-2.20 pyparsing-2.4.7 readme-renderer-29.0 requests-2.25.1 requests-toolbelt-0.9.1 rfc3986-1.4.0 six-1.15.0 tqdm-4.60.0 twine-3.4.1 urllib3-1.26.4 webencodings-0.5.1 zipp-3.4.1
```

#### But when it gets to  the Build and publish section it fails with  "error: invalid command 'bdist_wheel'"

```
Run python setup.py sdist bdist_wheel
  python setup.py sdist bdist_wheel
  twine upload --repository testpypi dist/*
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.4/x64/lib
    TWINE_USERNAME: ***
    TWINE_PASSWORD: ***
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
Error: Process completed with exit code 1.
```
