### ISSUE TITLE
Example about how to securely login through Docker CLI

### ISSUE THREAD

**Issue by eine** [actions/starter-workflows#96]
Currently, using `echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin` produces a warning:

```
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Login Succeeded
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

Please, provide an example workflow, step or action that allows to securely login through Docker CLI.

**Comment by chrispat** [comment]
Azure has published an action that does a secure docker login https://github.com/Azure/k8s-actions/tree/master/docker-login

**Comment by 1138-4EB** [comment]
@chrispat, thanks for the reference! Unfortunately, the action provided by Azure is at least as bad as using 'docker login' directly, if not worse. The point is that docker login explicitly warns the user about the configuration being stored unencrypted. Azure, however, does not show any warning, despite the underlying storage mechanism being the almost the same. Please, bear with me:

- https://github.com/Azure/k8s-actions/tree/master/docker-login contains a deprecation note that includes a (broken) link to https://github.com/Azure/container-actions/tree/master
- Subdir [docker-login](https://github.com/Azure/container-actions/tree/master/docker-login) contains the, seemingly up-to-date action.
- If we check the JavaScript source (https://github.com/Azure/container-actions/blob/master/docker-login/lib/login.js#L21-L34) of the action, we find that:

```js
        let authenticationToken = new Buffer(`${username}:${password}`).toString('base64');
        let config = { "auths": { [loginServer]: { auth: authenticationToken } } };
...
        fs.writeFileSync(dockerConfigPath, JSON.stringify(config));
        command_1.issueCommand('set-env', { name: 'DOCKER_CONFIG' }, dirPath);
```

Therefore, the only practical difference is that Azure stores the config file in `path.join(runnerTempDirectory, ``docker_login_${Date.now()}``)`, instead of `/home/runner/.docker/config.json`.

Furthermore, this was brought by @TingluoHuang a week ago (see Azure/container-actions#3).

**Comment by chrispat** [comment]
Beyond making sure the docker config is cleaned up after the job I am not sure there are any other options that will work in an automated sceanrio.  In the end the docker client needs to be able to read the credential in order to pull and push containers.  Even if the credential was stored in a credstore that would need to be accessible by the user the docker process is running under so you would have the same potential security issue you have today.  

I suppose you could have actions that handle pull and push for you that take the crednetial and then use a cred helper that reads from the environment.  However, then simple things like docker build or docker run just pulling the image would be more difficult.

**Comment by 1138-4EB** [comment]
> Beyond making sure the docker config is cleaned up after the job I am not sure there are any other options that will work in an automated sceanrio.

I think that a safer procedure is not to write any sensible unencrypted data to disk, in first place. It is compulsory to clean up after the job is done, of course. But there are four possible contexts with different places to clean up:

1. Raw data in disk.
2. Raw data in memory.
3. Encrypted data in disk.
4. Encrypted data in memory.

Currently, only 1 seems to be possible with GitHub/Azure Actions.

> In the end the docker client needs to be able to read the credential in order to pull and push containers.

Yes. Precisely, credential stores allow to hold encrypted data in memory and only provide it to the authorized user/service/tool that has the corresponding key. And credential helpers allow the docker client to be able to read from credential stores.

> Even if the credential was stored in a credstore that would need to be accessible by the user the docker process is running under so you would have the same potential security issue you have today.

I am not sure I understand this. I'd say the the risk of any unauthorized user to read some raw data that has been written to disk (either while it is being used or after it was expectedly removed from a `tmp` dir) is higher than the same user accessing the memory space of an application at runtime. I expect the memory to be overwritten/reused more frequently. Of course, if the attacker can gain control of your user, you are lost, no matter how secure the procedure.
 
> I suppose you could have actions that handle pull and push for you that take the crednetial and then use a cred helper that reads from the environment. However, then simple things like docker build or docker run just pulling the image would be more difficult.

`docker build` and `docker run` don't need credentials at all. It is irrelevant if a credential helper exists, whether it is running or crashed. The credential helper only needs to be setup between `docker login` and `docker logout` to execute `docker push` (or to `docker pull` from a private registry). E.g.

```
- run: docker pull <public_image>
- run: docker build -t <test_image>...
- run: docker run ...<test_image>...
- run: docker build -t <image>...
- uses: azure/container-actions/docker-securelogin@master
  with:
    username: '<username>'
    password: '<password>'
- run: docker push <image>
- uses: azure/container-actions/docker-securelogout@master
```

or

```
- uses: azure/container-actions/docker-securelogin@master
  with:
    username: '<username>'
    password: '<password>'
- run: docker pull <private_image>
- uses: azure/container-actions/docker-securelogout@master
- run: docker build -t <test_image>...
- run: docker run ...<test_image>...
- run: docker build -t <image>...
- uses: azure/container-actions/docker-securelogin@master
  with:
    username: '<username>'
    password: '<password>'
- run: docker push <image>
- uses: azure/container-actions/docker-securelogout@master
```

Ref: https://github.com/docker/docker-credential-helpers/blob/master/ci/before_script_linux.sh
